"""GitHub OAuth flow for hacker identity verification.

The two routes here implement the standard OAuth "authorization code"
flow:
  1. /github/login redirects the browser to GitHub's consent screen.
  2. GitHub redirects back to /github/callback with a one-time `code`.
  3. This module exchanges that code for an access token server-to-
     server, fetches the GitHub user's profile with it, upserts a
     Hacker row, and hands the SPA a TruPitch-issued session JWT.

There is no persistent server-side "login session" — once the callback
finishes, the JWT (see core/security.py) is the only thing proving who
the hacker is on every later request.
"""

import logging
from datetime import datetime, timedelta, timezone

import httpx
import jwt
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from core.config import settings
from core.database import get_db
from core.security import create_access_token
from models import Hacker

# How long a login attempt has to complete the GitHub round-trip before
# its `state` token (see below) is considered expired.
STATE_TTL = timedelta(minutes=10)


def _issue_state(next_path: str) -> str:
    """Short-lived signed token proving the OAuth flow started with us.

    This is the OAuth "state" parameter, used for CSRF protection: it's
    generated by /github/login and must come back unchanged (and
    unexpired) to /github/callback, or the callback refuses to proceed.
    Because it's a JWT signed with our own secret, we don't need a
    database or session store to validate it later — decoding it
    successfully *is* the proof it's genuine.

    Carries the SPA path to return to after login.
    """
    now = datetime.now(timezone.utc)
    return jwt.encode(
        {
            "purpose": "oauth_state",
            "next": next_path,
            "iat": now,
            "exp": now + STATE_TTL,
        },
        settings.jwt_secret,
        algorithm="HS256",
    )


def _check_state(state: str | None) -> dict:
    """Decode and validate the `state` param from GitHub's callback
    redirect. Raises a 400 on anything wrong: missing, expired, forged,
    or (via the "purpose" check) a stray JWT of the wrong kind — this
    same secret also signs hacker session tokens in core/security.py,
    so we make sure we're not accidentally accepting one of those here.
    """
    try:
        payload = jwt.decode(
            state or "", settings.jwt_secret, algorithms=["HS256"]
        )
        if payload.get("purpose") != "oauth_state":
            raise jwt.InvalidTokenError("wrong purpose")
        return payload
    except jwt.InvalidTokenError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid or expired OAuth state; restart the login flow",
        )


def _safe_next(next_path: str) -> str:
    """Only same-origin SPA paths; anything else falls back to home.

    `next_path` ultimately comes from a query parameter a client
    controls, so without this check a crafted login link could redirect
    a hacker's browser (carrying their fresh session token in the URL)
    to an attacker's site. Requiring a path that starts with exactly one
    "/" keeps it to same-origin, relative navigation only.
    """
    if next_path.startswith("/") and not next_path.startswith("//"):
        return next_path
    return "/"

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/auth", tags=["auth"])

GITHUB_AUTHORIZE_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_USER_URL = "https://api.github.com/user"


@router.get("/github/login")
async def github_login(next: str = "/") -> RedirectResponse:
    """Send the hacker to GitHub's consent screen.

    `next` is the SPA path to return to after authentication — e.g. the
    event page a hacker clicked "Authenticate with GitHub" from, so
    login doesn't dump them back on the homepage having lost their place.
    """
    if not settings.github_client_id:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="GITHUB_CLIENT_ID is not configured",
        )
    return RedirectResponse(
        f"{GITHUB_AUTHORIZE_URL}"
        f"?client_id={settings.github_client_id}&scope=repo"
        f"&state={_issue_state(_safe_next(next))}"
    )


@router.get("/github/callback")
async def github_callback(
    code: str, state: str | None = None, db: AsyncSession = Depends(get_db)
) -> RedirectResponse:
    """Exchange the OAuth code, upsert the hacker, hand a JWT to the SPA.

    GitHub redirects the browser here after the user approves (or
    denies) the OAuth consent screen, with `code` and our own `state`
    attached as query parameters.
    """
    # Reject forged/expired/replayed callbacks before doing anything
    # that talks to GitHub or touches the database.
    state_payload = _check_state(state)
    next_path = _safe_next(state_payload.get("next", "/"))
    async with httpx.AsyncClient(timeout=15.0) as client:
        try:
            # Server-to-server exchange: trade the one-time `code` for a
            # real access token. This request includes our client_secret,
            # which is why it must happen from the backend and never
            # from the browser directly.
            token_resp = await client.post(
                GITHUB_TOKEN_URL,
                data={
                    "client_id": settings.github_client_id,
                    "client_secret": settings.github_client_secret,
                    "code": code,
                },
                headers={"Accept": "application/json"},
            )
        except httpx.HTTPError as exc:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"GitHub token exchange failed: {exc}",
            )

        access_token = (
            token_resp.json().get("access_token")
            if token_resp.status_code == 200
            else None
        )
        if not access_token:
            # A bad/expired/already-used `code`, or a misconfigured
            # client_secret, both show up here as "no access_token".
            logger.warning("OAuth exchange rejected: %s", token_resp.text[:200])
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="GitHub rejected the OAuth code",
            )

        try:
            # Fetch the profile of whoever this access token belongs to,
            # so we know which GitHub account just logged in.
            user_resp = await client.get(
                GITHUB_USER_URL,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/vnd.github+json",
                },
            )
        except httpx.HTTPError as exc:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"GitHub user lookup failed: {exc}",
            )

    if user_resp.status_code != 200:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Could not fetch GitHub user profile",
        )
    user = user_resp.json()
    github_id = str(user["id"])
    username = user["login"]

    # Upsert by github_id (stable) rather than username (can change):
    # first login creates the Hacker row, every login after that just
    # refreshes the username/token on the existing row.
    hacker = (
        await db.execute(select(Hacker).where(Hacker.github_id == github_id))
    ).scalar_one_or_none()
    if hacker is None:
        hacker = Hacker(
            github_id=github_id, username=username, github_token=access_token
        )
        db.add(hacker)
    else:
        hacker.username = username
        hacker.github_token = access_token
    await db.commit()
    await db.refresh(hacker)

    # Hand the SPA a TruPitch session JWT (not the GitHub token itself —
    # that stays server-side) by putting it in the redirect's query
    # string; the frontend picks it up and stores it (see lib/auth.ts).
    jwt_token = create_access_token(hacker.id)
    return RedirectResponse(f"{settings.frontend_url}{next_path}?token={jwt_token}")
