// Pulls in Vite's ambient type declarations (import.meta.env, asset
// imports like *.svg, etc.) so TypeScript recognizes Vite-specific
// syntax across the project. Auto-generated by `npm create vite` and
// not meant to be edited.
/// <reference types="vite/client" />
