"""add_hacker_and_oauth

Revision ID: 472877f5ea5f
Revises: 50071a317017
Create Date: 2026-07-13 21:07:35.544468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472877f5ea5f'
down_revision: Union[str, None] = '50071a317017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('github_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackers_github_id'), 'hackers', ['github_id'], unique=True)
    op.add_column('submissions', sa.Column('hacker_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_submissions_hacker_id'), 'submissions', ['hacker_id'], unique=False)
    op.create_foreign_key(None, 'submissions', 'hackers', ['hacker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_index(op.f('ix_submissions_hacker_id'), table_name='submissions')
    op.drop_column('submissions', 'hacker_id')
    op.drop_index(op.f('ix_hackers_github_id'), table_name='hackers')
    op.drop_table('hackers')
    # ### end Alembic commands ###
