"""add_notes_to_submission

Revision ID: 50071a317017
Revises: 64b3a5527329
Create Date: 2026-07-12 22:59:00.270305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50071a317017'
down_revision: Union[str, None] = '64b3a5527329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('notes', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'notes')
    # ### end Alembic commands ###
